package com.yushilei.xmly4fm.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yushilei.xmly4fm.entities.AlbumEntity;
import com.yushilei.xmly4fm.entities.RecommendEntity;
import com.yushilei.xmly4fm.entities.TrackEntity;
import com.yushilei.xmly4fm.entities.FocusImageEntity;
import com.yushilei.xmly4fm.entities.DiscoveryEntity;
import com.yushilei.xmly4fm.entities.SpecialEntity;

import com.yushilei.xmly4fm.dao.AlbumEntityDao;
import com.yushilei.xmly4fm.dao.RecommendEntityDao;
import com.yushilei.xmly4fm.dao.TrackEntityDao;
import com.yushilei.xmly4fm.dao.FocusImageEntityDao;
import com.yushilei.xmly4fm.dao.DiscoveryEntityDao;
import com.yushilei.xmly4fm.dao.SpecialEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig albumEntityDaoConfig;
    private final DaoConfig recommendEntityDaoConfig;
    private final DaoConfig trackEntityDaoConfig;
    private final DaoConfig focusImageEntityDaoConfig;
    private final DaoConfig discoveryEntityDaoConfig;
    private final DaoConfig specialEntityDaoConfig;

    private final AlbumEntityDao albumEntityDao;
    private final RecommendEntityDao recommendEntityDao;
    private final TrackEntityDao trackEntityDao;
    private final FocusImageEntityDao focusImageEntityDao;
    private final DiscoveryEntityDao discoveryEntityDao;
    private final SpecialEntityDao specialEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        albumEntityDaoConfig = daoConfigMap.get(AlbumEntityDao.class).clone();
        albumEntityDaoConfig.initIdentityScope(type);

        recommendEntityDaoConfig = daoConfigMap.get(RecommendEntityDao.class).clone();
        recommendEntityDaoConfig.initIdentityScope(type);

        trackEntityDaoConfig = daoConfigMap.get(TrackEntityDao.class).clone();
        trackEntityDaoConfig.initIdentityScope(type);

        focusImageEntityDaoConfig = daoConfigMap.get(FocusImageEntityDao.class).clone();
        focusImageEntityDaoConfig.initIdentityScope(type);

        discoveryEntityDaoConfig = daoConfigMap.get(DiscoveryEntityDao.class).clone();
        discoveryEntityDaoConfig.initIdentityScope(type);

        specialEntityDaoConfig = daoConfigMap.get(SpecialEntityDao.class).clone();
        specialEntityDaoConfig.initIdentityScope(type);

        albumEntityDao = new AlbumEntityDao(albumEntityDaoConfig, this);
        recommendEntityDao = new RecommendEntityDao(recommendEntityDaoConfig, this);
        trackEntityDao = new TrackEntityDao(trackEntityDaoConfig, this);
        focusImageEntityDao = new FocusImageEntityDao(focusImageEntityDaoConfig, this);
        discoveryEntityDao = new DiscoveryEntityDao(discoveryEntityDaoConfig, this);
        specialEntityDao = new SpecialEntityDao(specialEntityDaoConfig, this);

        registerDao(AlbumEntity.class, albumEntityDao);
        registerDao(RecommendEntity.class, recommendEntityDao);
        registerDao(TrackEntity.class, trackEntityDao);
        registerDao(FocusImageEntity.class, focusImageEntityDao);
        registerDao(DiscoveryEntity.class, discoveryEntityDao);
        registerDao(SpecialEntity.class, specialEntityDao);
    }
    
    public void clear() {
        albumEntityDaoConfig.getIdentityScope().clear();
        recommendEntityDaoConfig.getIdentityScope().clear();
        trackEntityDaoConfig.getIdentityScope().clear();
        focusImageEntityDaoConfig.getIdentityScope().clear();
        discoveryEntityDaoConfig.getIdentityScope().clear();
        specialEntityDaoConfig.getIdentityScope().clear();
    }

    public AlbumEntityDao getAlbumEntityDao() {
        return albumEntityDao;
    }

    public RecommendEntityDao getRecommendEntityDao() {
        return recommendEntityDao;
    }

    public TrackEntityDao getTrackEntityDao() {
        return trackEntityDao;
    }

    public FocusImageEntityDao getFocusImageEntityDao() {
        return focusImageEntityDao;
    }

    public DiscoveryEntityDao getDiscoveryEntityDao() {
        return discoveryEntityDao;
    }

    public SpecialEntityDao getSpecialEntityDao() {
        return specialEntityDao;
    }

}
