package com.yushilei.xmly4fm.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.yushilei.xmly4fm.entities.RecommendEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECOMMEND_ENTITY".
*/
public class RecommendEntityDao extends AbstractDao<RecommendEntity, Long> {

    public static final String TABLENAME = "RECOMMEND_ENTITY";

    /**
     * Properties of entity RecommendEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property ContentType = new Property(2, String.class, "contentType", false, "CONTENT_TYPE");
        public final static Property IsFinished = new Property(3, Boolean.class, "isFinished", false, "IS_FINISHED");
        public final static Property CategoryId = new Property(4, Integer.class, "categoryId", false, "CATEGORY_ID");
        public final static Property Count = new Property(5, Integer.class, "count", false, "COUNT");
        public final static Property HasMore = new Property(6, Boolean.class, "hasMore", false, "HAS_MORE");
    };


    public RecommendEntityDao(DaoConfig config) {
        super(config);
    }
    
    public RecommendEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECOMMEND_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"CONTENT_TYPE\" TEXT," + // 2: contentType
                "\"IS_FINISHED\" INTEGER," + // 3: isFinished
                "\"CATEGORY_ID\" INTEGER," + // 4: categoryId
                "\"COUNT\" INTEGER," + // 5: count
                "\"HAS_MORE\" INTEGER);"); // 6: hasMore
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECOMMEND_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RecommendEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String contentType = entity.getContentType();
        if (contentType != null) {
            stmt.bindString(3, contentType);
        }
 
        Boolean isFinished = entity.getIsFinished();
        if (isFinished != null) {
            stmt.bindLong(4, isFinished ? 1L: 0L);
        }
 
        Integer categoryId = entity.getCategoryId();
        if (categoryId != null) {
            stmt.bindLong(5, categoryId);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(6, count);
        }
 
        Boolean hasMore = entity.getHasMore();
        if (hasMore != null) {
            stmt.bindLong(7, hasMore ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RecommendEntity readEntity(Cursor cursor, int offset) {
        RecommendEntity entity = new RecommendEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // contentType
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // isFinished
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // categoryId
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // count
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0 // hasMore
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RecommendEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContentType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsFinished(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setCategoryId(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setCount(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setHasMore(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RecommendEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RecommendEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
