package com.yushilei.xmly4fm.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.List;

/**
 * Entity mapped to table "RECOMMEND_ENTITY".
 */
public class RecommendEntity {

    private Long id;
    private String title;
    private String contentType;
    private Boolean isFinished;
    private Integer categoryId;
    private Integer count;
    private Boolean hasMore;
    private List<AlbumEntity> list;

    public List<AlbumEntity> getList() {
        return list;
    }

    public void setList(List<AlbumEntity> list) {
        this.list = list;
    }

    public RecommendEntity() {
    }

    public RecommendEntity(Long id) {
        this.id = id;
    }

    public RecommendEntity(Long id, String title, String contentType, Boolean isFinished, Integer categoryId, Integer count, Boolean hasMore) {
        this.id = id;
        this.title = title;
        this.contentType = contentType;
        this.isFinished = isFinished;
        this.categoryId = categoryId;
        this.count = count;
        this.hasMore = hasMore;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public Boolean getIsFinished() {
        return isFinished;
    }

    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    public Integer getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Boolean getHasMore() {
        return hasMore;
    }

    public void setHasMore(Boolean hasMore) {
        this.hasMore = hasMore;
    }

}
